//! The committed JSON sample is generated by the same library API consumers use.

#![allow(clippy::expect_used)]

use std::fs;
use std::path::Path;

use orbit_graph_changes::report::{ReportOptions, build_report};
use orbit_graph_changes::snapshot::Comparison;

mod common;

use common::corpus;

const SAMPLE_GENERATED_AT: &str = "2026-09-13T00:00:00Z";
const REGENERATE: &str =
    "UPDATE_GOLDENS=1 cargo test -p orbit-graph-changes --test derived_artifacts --locked";

#[test]
fn committed_direct_call_json_is_a_fresh_regeneration() {
    let case = corpus::build_case("direct-call");
    let comparison =
        Comparison::open(&case.repository, case.base(), case.head()).expect("open comparison");
    let options = ReportOptions {
        generated_at: Some(SAMPLE_GENERATED_AT.to_string()),
        ..ReportOptions::default()
    };
    let report = build_report(&comparison, &options).expect("build report");
    let fresh = serde_json::to_string_pretty(&report).expect("serialize report");
    let committed_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../docs/evaluation/change-explorer/samples/direct-call.json");
    if std::env::var_os("UPDATE_GOLDENS").is_some_and(|value| value == "1") {
        fs::write(committed_path, fresh).expect("rewrite sample");
        return;
    }
    let committed = fs::read_to_string(committed_path).expect("read committed sample");
    assert_eq!(
        committed, fresh,
        "JSON sample is stale; regenerate with {REGENERATE}"
    );
}
